### PR TITLE
Refactor and update App

### PR DESCRIPTION
**Pull request by natec8**
Refactors and updates the entire app:

- Updates the `react-dates`, `babel` and other dependencies
- Breaks out each individual part into separate components
- Uses React hooks to manage state, context and life cycle events
- Updates the example to use webpack dev server with hot module loading
and react hot loader
- Renames the lib/ folder to dist/
- Renames the moduels/ folder to src/
- Uses an inline SVG for the calendar icon
- Integrates Prettier

### CODE REVIEW

**Comment by rsahlstrom** [comment]
I'm looking at this today

**Review by rsahlstrom — CHANGES_REQUESTED** [review]
These look like good changes to me. One small question about end time on ranges in the comments.

I also was able to get it to not show the selected range when opening the calendar with these steps. I'm not sure what the values are for end date and start date when this happens but I assume it's what the input it showing and not what the calendar has selected.

1. In the example, select a valid date range
2. See the dates in the input
3. Open up the calendar selection again and pick a single date
4. Click outside of the calendar
5. Date range in the input is the same as 2
6. Open the calendar
7. Date range selected and shown on the calendar is the single date selected in 3

**Comment by rsahlstrom** [comment]
If these aren't a big deal and you want this merged and we can handle this in a different PR if warranted, let me know.

**Review by rsahlstrom — CHANGES_REQUESTED** [review]
This is still acting weird for me. At times, when I select a range, it will ignore my end date and instead make the range start and end on the same day. Steps to reproduce:

1. Run `yarn start`
2. Hit up the example page and pick any input
3. Select a date range
4. It works great.
5. Open up the exact same input and select a new date range
6. The date range start and end date are now the same. Your selected end date for the range is ignored.
7. Reject the pull request

**Comment by natec8** [comment]
@rsahlstrom The issue you reported should be fixed now.

**Review by rsahlstrom — APPROVED** [review]
Everything's working! Thanks for your hard work on this.

**Pull request merged**
